### ISSUE TITLE
🕯️ Banner Image flickers in Reading View

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pixel-banner#33]
In some cases, the Banner image keeps flickering.
What I tested:
1. When scrolling the page
![4c46b92c-e855-4e59-bfdc-412d520cd2ff](https://github.com/user-attachments/assets/c1fd646c-9f2c-447c-b704-7a166d936fee)

2. Hold down Ctrl and call **Hover Editor** plugin to preview the note
![d35dfb7c-6145-4aad-b330-cb085737181f](https://github.com/user-attachments/assets/3d271d45-8e82-4edb-9583-dd48b17cf8df)

It seems that this bug was fixed before, but now it appears again 🤔

**Comment by Moyf** [comment]
Additional information: This issue seems to only occur within the reading view

**Comment by jparkerweb** [comment]
The issue exists because of the way Obsidian is managing its Virtual DOM. It is trying to be efficient and remove items it thinks are no longer in view, etc.  I can prevent this behavior by moving the banner image to a more stable/safer portion of the page (outside of the note content), but then the image becomes "sticky" and won't scroll with your note content.  I am looking into alternative solutions, but for now we will have to live with the re-inserting of the banner after it gets removed by Obsidian.  I have added a fade-in animation to try to prevent a sudden flash and make it a little more appealing (maybe the fade-in duration could be a setting the user could control?).  anyway, stay tuned on this one, but no clear path forward ATM.

If anyone has ideas please let me know.

**Comment by Moyf** [comment]
我不确定是否有关联……不过在我之前使用 NoteToolbar 插件的时候，也遇到过类似不断闪烁的问题。
幸运的是 NTB 的开发者最近解决了这个问题，这是当时我们讨论的 Issue，希望能提供一些帮助：
https://github.com/chrisgurney/obsidian-note-toolbar/issues/14#issuecomment-2420294645

**Comment by jparkerweb** [comment]
@Moyf
Update the plugin and see if 2.2.3 fixes the flicker for you please 🤞

**Comment by jparkerweb** [comment]
actually, hold off found a bug, need to roll that back

**Comment by jparkerweb** [comment]
Ok, I think we are ok now.
Let me know if 2.2.4 doesn't fix it for you.

**Comment by jparkerweb** [comment]
@Moyf 
sorry for the delay, did quite a bit of testing.
Please update and try now
