### ISSUE TITLE
❓ Content start doesn't work

### ISSUE THREAD

**Issue by camo200sx** [jparkerweb/pixel-banner#47]
For some reason content-start has no affect in my vault. Has this been encountered before?

**Comment by jparkerweb** [comment]
what version of 🚩 Pixel Banner are you using?
A bug was introduced in v2.6.0 and fixed in 2.6.4 for this specific issue:
https://github.com/jparkerweb/pixel-banner/releases/tag/2.6.4

![image](https://github.com/user-attachments/assets/6f699471-6572-48d3-a273-1d545a12d9d5)

If you are on version 2.6.4 already can you please open dev tools (ctrl/cmd + i) and see if you notice any errors in the console tab?
Additionally, download and open the example vault in this repo and see if it behaves properly there:
https://github.com/jparkerweb/pixel-banner/blob/main/example-vault.zip

Looking forward to helping you resolve your issue.

**Comment by jparkerweb** [comment]
## Example setting Content Start via Folder Image Settings
![Image](https://github.com/user-attachments/assets/139dbf72-c900-4fd6-b193-9a3386cbba0a)

**Comment by jparkerweb** [comment]
## Example controlling Content Start via General settings
![Image](https://github.com/user-attachments/assets/207deca8-7f6f-43e1-bac9-018056702be6)

**Comment by camo200sx** [comment]
@jparkerweb . Thanks Justin! I downloaded from the community plug-ins but I guess it wasn't the latest version. Going back in and the update was available. Looking good now.
