### ISSUE TITLE
problem with the display

### ISSUE THREAD

**Issue by fayzzz1229** [jparkerweb/pixel-banner#78]
When I input "---", it will automatically transform to a table summarising the property like this
![image](https://github.com/user-attachments/assets/5983358c-81c2-44b6-ae1f-1fe4ba9d309d)

**Comment by jparkerweb** [comment]
@fayzzz1229 
This has nothing to do with any plugin, but the normal behavior of Obsidian and `frontmatter` fields.
If any note starts with `---` it is the start of `frontmatter`.  You are seeing the `properties` section because you are in Live Preview mode.  If you don't want any `frontmatter` and want your first entries to be a line (`---`), you can just add a blank line for the first line value.  Look at this example video:


https://github.com/user-attachments/assets/e2946dde-90fe-4fd6-8814-fbaa264e498f

**Comment by fayzzz1229** [comment]
Thanks a lot! It works pretty well now. Fantastic plug-in :)
