### ISSUE TITLE
🐛 ...No pictures from e.g. Pexel or Unsplash are showing

### ISSUE THREAD

**Issue by eriktams** [jparkerweb/pixel-banner#96]
I have inserted an API key and it works fine. However, when I try to search for images using the normal search bar no images from Pexel or unsplash are showing. Am I doing something wrong?

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. I would have thought that I could search for a picture in the Unsplash database or the Pexel database but I cannot find any pictures from them, when I try to search for a picture in the plugin-

**Screenshots**
If applicable, add screenshots or any example vault (.zip) to help explain your problem.
![image](https://github.com/user-attachments/assets/938d01d2-e58f-4e22-a2d2-7cb2e181130e)

**Environment:**
 - OS: [Windows]
 - Obsidian Version (if applicable): [e.g. 1.7.7]
 - Other Details: 

**Additional context**

**Comment by jparkerweb** [comment]
@eriktams 
Thank you for submitting an issue.

You are not doing anything wrong. The issue is that the Banner Select modal is for selecting an image from your vault or uploading an image from your computer, etc.

I am adding a small description to that model to help clarify this a bit more in the next release.
Thank you again, and sorry for any confusion:

![image](https://github.com/user-attachments/assets/ff747baa-1d05-4680-a462-d35c4638e785)
